baseURL = 'https://blog.l33chers.de/'
languageCode = 'en-us'
title = 'l33chers team blog'
theme = 're-terminal'
publishDir = 'docs'

[outputs]
home = ["HTML", "JSON"]

[menu]
[[menu.main]]
name = "Search"
url = "/search/"
weight = 100

[params]
[params.giscus]
repo = "l33chers/blog.l33chers.de"
repoId = "R_kgDOQ1jI9w"
category = "Q&A"
categoryId = "DIC_kwDOQ1jI984C0sRm"
mapping = "pathname"
strict = "1"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "dark"
lang = "en"
loading = "lazy"
